name: Build for Windows x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        run: choco install ninja

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache the build
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build
        run: cmake --build build --config Release --parallel 4

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/plugin/LEVEL3_artefacts/Release/VST3
